### ISSUE TITLE
接口请求失败

### ISSUE THREAD

**Issue by a807966224** [alldatacenter/alldata#313]
http://43.138.157.47:8013/login?redirect=%2Fdashboard

下面的接口报错了，帮忙看下

curl "http://43.138.157.47:8013/auth/code" ^
  -H "Accept: application/json, text/plain, */*" ^
  -H "Accept-Language: zh-CN,zh;q=0.9" ^
  -H "Connection: keep-alive" ^
  -H "Referer: http://43.138.157.47:8013/login?redirect=^%^2Fdashboard" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" ^
  --compressed ^
  --insecure

**Comment by alldatadc** [comment]
您好，此问题已近期修复，谢谢您
https://github.com/alldatacenter/alldata/pull/315
