### ISSUE TITLE
dynamic-datasource Please check the setting of primary，项目启动失败

### ISSUE THREAD

**Issue by zfthink** [alldatacenter/alldata#357]
![image](https://user-images.githubusercontent.com/68531131/218708963-1076ef6d-481e-47de-91c1-70045a92cd94.png)
如何正确配置让工程能找到config下的profile文件，从而使工程能启动成功

**Comment by zfthink** [comment]
目前各工程的配置文件统一放到了config工程下面了，那么在启动工程的时候，应该如何配置参数才能正确找到对应的配置文件从而启动工程

**Comment by alldatadc** [comment]
match the configuration file name in config #363
