### ISSUE TITLE
前端项目启动后访问登录页，上面出现未知弹框

### ISSUE THREAD

**Issue by zfthink** [alldatacenter/alldata#358]
![image](https://user-images.githubusercontent.com/68531131/218709964-de22f2ff-748a-4221-a937-d5cd0ae2c897.png)

**Comment by afeiyaya** [comment]
你好，解决了吗

**Comment by alldatadc** [comment]
https://github.com/alldatacenter/alldata/releases/tag/v0.3.5
问题未出现
