### ISSUE TITLE
部署文档错误

### ISSUE THREAD

**Issue by MorrisMing7** [alldatacenter/alldata#374]
README.md中“部署方式”下相关sql脚本在相关位置无法找到
例如
> source install/16gmaster/studio/studio_alldatadc.sql

**Comment by alldatadc** [comment]
#376 finished

**Comment by MorrisMing7** [comment]
我按照您链接中的安装部署文档，在项目根目录中找到 `factory/studio/install/16gmaster/studio/studio_alldatadc.sql` 这个文件与部署步骤1中的文件对应，
故推测步骤4中所指的“项目根目录”为`factory/studio`，请问这个推测是否正确；

依次到步骤4中，在`factory/studio`此目录下执行`mvn install`遇到如下错误

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (default) on project assembly: Failed to create assembly: Error creating assembly archive 0.3.2: Cannot transform line endings on this kind of file: 16gmaster/studio/aspose-words-20.3.jar
> [ERROR] Doing so is more or less guaranteed to destroy the file, and it indicates a problem with your assembly descriptor.
> [ERROR] This error message is new as of 2.5.3.
> [ERROR] Earlier versions of assembly-plugin will silently destroy your file. Fix your descriptor
> [ERROR] -> [Help 1]

请问是我哪里出了错误吗，还是说部署文档有问题？我该怎么解决这个错误


> #376 finished ![image](https://user-images.githubusercontent.com/20246692/220268942-1ea8a5c9-0f07-423a-9e2b-dd645c9fef37.png) 官方文档：https://alldata.readthedocs.io/en/master/factory/studio/README.html#id7
