### ISSUE TITLE
system服务启动报错

### ISSUE THREAD

**Issue by jinrong58** [alldatacenter/alldata#378]
基于2023年2月21日时的develop分支最新代码编译后的部署包，部署system模块启动时报如下错误，而无法启动。
***************************
APPLICATION FAILED TO START
***************************

Description:

Field jwtUtil in com.platform.utils.SecurityUtil required a bean of type 'com.platform.utils.JwtUtil' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.platform.utils.JwtUtil' in your configuration.

**Comment by jinrong58** [comment]
我找到工程里的com.platform.utils.JwtUtil文件了，给这个类添加@Component后编译部署system就能启动了。

**Comment by alldatadc** [comment]
You can submit PR
