### ISSUE TITLE
studio-web启动后,验证码不显示

### ISSUE THREAD

**Issue by moliqingwa** [alldatacenter/alldata#381]
通过启动方式: `npm run dev`
错误信息：http://localhost:8013/system/auth/code 接口 404错误

**Comment by afeiyaya** [comment]
你好，解决了吗

**Comment by moliqingwa** [comment]
没有解决，看样子是前后端分离导致的，解决了这个接口，还有其它的接口也会有相同的问题

**Comment by alldatadc** [comment]
您可以尝试提交PR，我们最新版本复现了这个问题，感谢

**Comment by alldatadc** [comment]
#459
