### ISSUE TITLE
元数据同步空指针异常

### ISSUE THREAD

**Issue by MYiYang** [alldatacenter/alldata#475]
1. 环境windows11
2. 数据库版本8.0.27
3. redis版本3.X
4. mq版本3.7.7

问题版本: 0.3.6~0.3.7

问题视频

https://user-images.githubusercontent.com/27657784/228714724-370dbe3c-6dbd-48cc-accf-27b2cf8407b3.mp4

该问题导致 无法进行元数据同步

**Comment by alldatadc** [comment]
您好，随时交流技术，6月底发版会修复此问题，感谢您

**Comment by alldatadc** [comment]
AllData Release V0.3.9已解决相关问题
#475 finished
