### ISSUE TITLE
v0.3.7中getway启动报redis连接不上（日志打印出的地址固定了localhost，没跟配置文件来）

### ISSUE THREAD

**Issue by 450316487** [alldatacenter/alldata#486]
![image](https://user-images.githubusercontent.com/40660640/232290216-22ff1835-dd60-4b39-930e-775e7206d250.png)
![image](https://user-images.githubusercontent.com/40660640/232290195-bc04443a-af3c-4870-a752-dd6b87362741.png)
我远程的redis确定是能访问的，但是getway启动时日志打印显示，redis没安装我配置的地址来，希望作者大大帮忙看看什么情况o(╥﹏╥)o

**Comment by alldatadc** [comment]
release v0.3.8 finished
