### ISSUE TITLE
期待数据流程模块实现逻辑功能的闭环

### ISSUE THREAD

**Issue by Sherlock-Xpf** [alldatacenter/alldata#488]
### 当前版本问题
1. 测试流程编排模块中的流程实例和任务列表 打开都是空白的页面 

2. 数据模型模块和测试流程编排模块中无法实现闭环。新建的数据模型提交发布之后再流程编排中不会显示对应要审批的任务

3. 流程定义中必需要要上传.bpmn20.xml结尾的文件么？可不可以实现快速手动创建？

**Comment by alldatadc** [comment]
LGTD,您好,由于数据流程编排模块沿用eladmin模块,后续会集成新的任务流功能,届时会发版,感谢
