### ISSUE TITLE
社区版数据集成配置教程

### ISSUE THREAD

**Issue by wsczm** [alldatacenter/alldata#489]
社区版数据集成配置教程

**Comment by Gresdy** [comment]
先找到用户管理-菜单管理，新增【数据集成】目录，之后再新增【数据集成】下面的菜单，菜单各项按如下配置输入，之后进入角色管理，配置admin账号的目录数据权限，选中刚才新增的数据集成目录及里面的菜单，刷新或重新登录即可访问【数据集成】
![image](https://user-images.githubusercontent.com/9457212/233446739-41ea4501-bb09-4eb2-86de-21c168784564.png)

![image](https://user-images.githubusercontent.com/9457212/233446763-cbb15105-b209-4b8f-b3f2-c41b5a607dd9.png)

![image](https://user-images.githubusercontent.com/9457212/233447516-c952efd0-f8e2-4181-8608-1f513f9c0e93.png)

**Comment by alldatadc** [comment]
fixed #493 
thanks a lot

**Comment by Gresdy** [comment]
您好, 您的邮件永宏已经收到！
