### ISSUE TITLE
部署時出現依賴問題

### ISSUE THREAD

**Issue by chn112211** [alldatacenter/alldata#494]
Failed to execute goal on project common-mybatis: Could not resolve dependencies for project common-mybatis: jar:0.3.6: Failed to collect dependencies at com. baomidou:dynamic-datasource-spring-boot-starttled to read' artifact descriptor for com. baomidou:dynamic-datasource-spring-boot-starter:jar:3.2: 1: The its could not be resolved: com. fasterxml. jackson: jackson-bom:pom:2.8.8 (absent): Could not transfer artii.. jackson: jackson-bom:pom:2.8.8 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror fol(http://maven. aliyun.com/nexus/content/groups/public/, default, releasestsnapshots)] -> [Help 1.

**Comment by alldatadc** [comment]
尝试删除本地repository/com/platform,重新mvn clean install
Release v0.3.8 finished
