### ISSUE TITLE
元数据管理-数据源管理接口异常

### ISSUE THREAD

**Issue by wsczm** [alldatacenter/alldata#495]
元数据管理-数据源管理接口异常

**Comment by dbnc** [comment]
执行清除全部redis缓存的操作后，数据源管理为空
![image](https://user-images.githubusercontent.com/49666713/234195002-e34d66c3-dfba-4ee9-a070-20d8037dd68b.png)
怀疑是缓存未重新加载的原因

**Comment by alldatadc** [comment]
AllData Release V0.3.8 finished #495
<br/>
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/20246692/236450271-cd26e84b-3a87-4f88-a477-02f06b918f76.png">
<br/>
