### ISSUE TITLE
service-data-dts-dev配置问题

### ISSUE THREAD

**Issue by superman-lm** [alldatacenter/alldata#500]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/3378941/234754658-23655c92-5923-4ac7-9900-2b113bea1284.png">
这些参数，不了解相关的chunjun和datax的同学，不懂的配置以及需要搭建对应的环境。建议在部署文档中完善

**Comment by alldatadc** [comment]
使用新的issue,描述此教程文档问题 #555
