### ISSUE TITLE
Data-Dts mongo配置问题

### ISSUE THREAD

**Issue by superman-lm** [alldatacenter/alldata#501]
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/3378941/234755206-6dc68696-51f1-4a8b-b5e2-f7ad412eb2a0.png">
在项目中没有看到mongo配置的地方，启动微服务DataDtsServiceApplication提示mongo报错。

**Comment by alldatadc** [comment]
AllData Release V0.3.9已解决相关问题
#501 finished
