### ISSUE TITLE
0.3.8版本数据比对菜单栏缺失

### ISSUE THREAD

**Issue by Hezheng2023** [alldatacenter/alldata#507]
缺失数据对比菜单栏数据

<img width="315" alt="5be7a48650454b53e5950f7ff97be9a" src="https://user-images.githubusercontent.com/128333131/235083298-346d67e8-e508-47d0-aaef-ec19b0232953.png">

**Comment by alldatadc** [comment]
AllData Release V0.3.9已解决相关问题
#507 finished
