### ISSUE TITLE
0.3.8版本数据集成模块创建数据源后，在配置任务引擎里“数据源”中看不到任何已创建的数据源。

### ISSUE THREAD

**Issue by jinrong58** [alldatacenter/alldata#516]
![image](https://user-images.githubusercontent.com/26400243/236384664-df25723f-614c-4c54-95c2-7dc6930e0183.png)
0.3.8版本数据集成模块创建数据源后，在配置任务引擎里“数据源”中看不到任何已创建的数据源。

**Comment by alldatadc** [comment]
您好，这是重复缺陷，请关注原有的issue记录 #495

**Comment by jinrong58** [comment]
大佬，这俩好像不是同一个。我报这个是“数据集成”dts模块里的。

**Comment by jinrong58** [comment]
我看了下495，感觉这两不是同一bug，因为他们是不同的模块里的。我报这个是dts的，而且我找到了问题的原因，前台返回的取值不对，加上.data就可以了。



获取表名也有同样的问题，加上.data就可以渲染列表了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alldatacenter/alldata"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月5日(星期五) 下午3:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alldatacenter/alldata] 0.3.8版本数据集成模块创建数据源后，在配置任务引擎里“数据源”中看不到任何已创建的数据源。 (Issue #516)





 
您好，这是重复缺陷，请关注原有的issue记录 #495
