### ISSUE TITLE
数据集成模块字段映射优化建议

### ISSUE THREAD

**Issue by superman-lm** [alldatacenter/alldata#522]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/3378941/236596091-3b6c9dea-4a04-407e-9428-b79d1e20028a.png">
前端建议优化一下字段对应关系，可以是拖拽顺序对应关系，这样方便字段关系对应。

**Comment by MorrisMing7** [comment]
之前看过有个叫云雀的类似界面，也是没有字段映射，要是能加上那简直泰裤辣！

**Comment by alldatadc** [comment]
LGTD,我们后续会支持这个功能,感谢

**Comment by alldatafounder** [comment]
not planned
