### ISSUE TITLE
[Feature] 元数据管理-数据血缘查询-支持对接Datahub

### ISSUE THREAD

**Issue by Zengjc1** [alldatacenter/alldata#531]
请问数据血缘功能是没完善还是待开发状态?
(现在是前端写死的数据，没调后台接口)
并且页面只有一个搜索按钮。都不能选数据源。

**Comment by alldatadc** [comment]
感谢您提交issue,已确认是缺陷,这个问题我安排社区伙伴解决下

**Comment by jeff06143132** [comment]
您好咨询一下该功能完善计划什么时候？

**Comment by alldatafounder** [comment]
Not planned,下一个版本解决
