### ISSUE TITLE
v0.3.9 ui启动报Failed to compile问题

### ISSUE THREAD

**Issue by jeff06143132** [alldatacenter/alldata#557]
前置 - 
1、启动前是删除了pom.xml；
2、本地是V16版本的nodejs;

运行 -
1、启动后端相关服务；
2、启动前端npm run dev,报错：
multi ./node modules/.pnpm/webpack-dev-server3.1.3 webpack04.28.4/node modules/webpack-dev-server/clienthtp://192.168.0.118:8013/sockjs-node(webpack)/hot/dev-server.js ./src/main.js
Module not found: Error: Can't resolvebabel-loader'in D: workspaceldatacenter workspacelscit-datacenter-ui

原因 - 
前端UI对应nodejs版本是v10.15.3 , 需要切换版本，为开发方便，一遍采用nvm进行管理
1、卸载nodejs;
2、安装nvm -  https://www.jianshu.com/p/13c0b3ca7c71
3、安装v10.15.3版本： nvm install v10.15.3
4、根据实际切换版本：nvm use v10.15.3
5、安装依赖：npm install
6、启动前端：npm run dev

**Comment by alldatadc** [comment]
LGTD,thanks a lot
finished https://github.com/alldatacenter/alldata/commit/2b5bb46077399b4a52f8c5841c2ab6a439aadbcf
