### ISSUE TITLE
后端启动服务补充说明

### ISSUE THREAD

**Issue by jeff06143132** [alldatacenter/alldata#558]
1. 启动Eurake项目
找到factory/studio/eureka/src/main/java/cn/datax/eureka/DataxEurekaApplication.java 运行启动
浏览器访问 http://localhost:8610/

2. 启动Config项目
修改bootstrap.yml文件，本地运行时eureka配置处，改成localhost
找到factory/studio/config/src/main/java/cn/datax/config/DataxConfigApplication.java，运行启动

3. 启动Gateway项目
修改bootstrap.yml文件，本地运行时eureka配置处，改成localhost
找到factory/studio/gateway/src/main/java/cn/datax/gateway/DataxGatewayApplication.java，启动项目
启动完后，可以在Eureka中发现刚才启动的服务

4. 启动SystemService项目，本地运行时eureka配置处，改成localhost。及其他项目同理。
系统管理 - system-service-parent ~ system-service ~ SystemServiceApplication
数据集成 - service-data-dts-parent ~ service-data-dts ~ DataDtsServiceApplication
元数据管理 - data-metadata-service-parent ~ data-metadata-service ~ DataxMetadataApplication
元数据管理 - data-metadata-service-parent ~ data-metadata-service-console ~ DataxConsoleApplication
数据标准 - data-standard-service-parent ~ data-standard-service ~ DataxStandardApplication
数据质量 - data-quality-service-parent ~ data-quality-service ~ DataxQualityApplication
数据资产 - data-masterdata-service-parent ~ data-masterdata-service ~ DataxMasterdataApplication
数据市场 - data-market-service-parent ~ data-market-service ~ DataxMarketApplication
数据市场 - data-market-service-parent ~ data-market-service-integration ~ DataxIntegrationApplication
数据市场 - data-market-service-parent ~ data-market-service-mapping ~ DataxMappingApplication
数据对比 - data-compare-service-parent ~ data-compare-service ~ DataCompareApplication
BI报表 - data-visual-service-parent ~ data-visual-service ~ DataxVisualApplication
流程编排 - workflow-service-parent ~ workflow-service ~ DataxWorkflowApplication
系统监控 - system-service-parent ~ system-service ~ SystemServiceApplication
批量/定时任务 - quartz-service-parent ~ quartz-service ~ DataxQuartzApplication
代码生成 - codegen-service-parent ~ codegen-service ~ DataxCodeGenApplication
邮件服务 - email-service-parent ~ email-service ~ DataxMailApplication
文件服务 - file-service-parent ~ file-service ~ DataxFileApplication

**Comment by alldatadc** [comment]
LGTD,thanks a lot
finished https://github.com/alldatacenter/alldata/commit/2b5bb46077399b4a52f8c5841c2ab6a439aadbcf
