### ISSUE TITLE
Could not find artifact com.platform:common-core:pom:0.4.x in aliyunmaven (https://maven.aliyun.com/repository/public)

### ISSUE THREAD

**Issue by swencg** [alldatacenter/alldata#559]
启动项目时报这个错误，是为啥呀？
<parent>
        <artifactId>studio</artifactId>
        <groupId>com.platform</groupId>
        <version>0.4.x</version>

    </parent>这些信息在IDEA中红色报警，咋搞呀

**Comment by alldatadc** [comment]
您好,新版本v0.3.9没有复现这个问题,您可以重新下载最新的v0.3.9 Release包
