### ISSUE TITLE
建议把studio的服务注册发现框架换成nacos

### ISSUE THREAD

**Issue by Kingsuperyzy** [alldatacenter/alldata#563]
相比与Eureka：
(1)Nacos具备服务优雅上下线和流量管理（API+后台管理页面），而Eureka的后台页面仅供展示，需要使用api操作上下线且不具备流量管理功能。
(2)从部署来看，Nacos整合了注册中心、配置中心功能，把原来两套集群整合成一套，简化了部署维护
(3)从长远来看，Eureka开源工作已停止，后续不再有更新和维护，而Nacos在以后的版本会支持SpringCLoud+Kubernetes的组合，填补 2 者的鸿沟，在两套体系下可以采用同一套服务发现和配置管理的解决方案，这将大大的简化使用和维护的成本。同时来说,Nacos 计划实现 Service Mesh，是未来微服务的趋势
建议把当前这套框架切换到nacos

**Comment by alldatadc** [comment]
感谢您,随时交流技术,respect!!

**Comment by alldatadc** [comment]
not planned
