### ISSUE TITLE
能不能把需要配置主机名的地方抽象到一个配置文件中呢？

### ISSUE THREAD

**Issue by hepeitong** [alldatacenter/alldata#568]
![image](https://github.com/alldatacenter/alldata/assets/49541649/751a70ca-ed1b-4015-9dfd-59ea17cb6970)
如图所示，代码中很多地方需要配置主机名，如果我部署到新的服务器中，要不就要把服务器的主机名改成和这里一样，要不就需要挨着挨着改配置。太麻烦了。

**Comment by alldatadc** [comment]
感谢您，后续发版可以支持这个，随时交流技术

**Comment by ProductManage-Leo** [comment]
not planned
