### ISSUE TITLE
单机部署,eureka检测不到服务,studio启动异常

### ISSUE THREAD

**Issue by jackjiang517** [alldatacenter/alldata#575]
问题描述：config,eureka,gateway部署在同一台服务器,eureka找不到其他服务,导致studio启动异常

**Comment by alldatadc** [comment]
您好,已确认是问题,目前建议解决方案是把eureka,config,gateway分开3个服务器IP部署

**Comment by alldatadc** [comment]
您好,已确认是问题,目前建议解决方案是把eureka,config,gateway分开3个服务器IP部署

**Comment by ProductManage-Leo** [comment]
推荐eureka,config,gateway分开3个服务器IP部署，不使用单节点部署
