### ISSUE TITLE
datax 连接MySQL8 失败

### ISSUE THREAD

**Issue by librawyx** [alldatacenter/alldata#583]
通过datax连接MySQL8 数据库时报连接失败信息，尝试在datax中的reader、Writer将原来的MySQL5的驱动调整MySQL8，调整com.mysql.jdbc.Driver"为"com.mysql.cj.jdbc.Driver"，jdbc数据库连接中增加zeroDateTimeBehavior=CONVERT_TO_NULL和serverTimezone=PRC参数，但依然报错。请协助排查

**Comment by librawyx** [comment]
补充，测试环境Win11

**Comment by ProductManage-Leo** [comment]
not planned
