### ISSUE TITLE
数据集成-启动同步任务疑似死锁,api日志数据无法生成

### ISSUE THREAD

**Issue by librawyx** [alldatacenter/alldata#585]
![image](https://github.com/alldatacenter/alldata/assets/133637627/8bd10991-4f44-43a5-a25d-03e9c4a61c01)
在任务详情中点击执行一次来实现数据同步（datax），可在控制台打印执行命令，
![image](https://github.com/alldatacenter/alldata/assets/133637627/b314090d-48b3-41f9-9098-952a3d4ccfb4)
该命令可在cmd中成功执行，但在工程中只有当DataDtsServiceApplication服务结束后才能成功被执行。
考虑进程死锁的原因，将代码尝试通过异步或多线程的方法进行改造，但效果不理想。代码如下：
public static void runJob(int jobId) {
		try {
			JobInfo jobInfo = JobAdminConfig.getAdminConfig().getJobInfoMapper().loadById(jobId);
			String cmdstr = "";
			String tmpFilePath ="";
			String[] cmdarrayFinal = null;
			tmpFilePath = generateTemJsonFile(jobInfo.getJobJson());
			cmdarrayFinal = buildFlinkXExecutorCmd(ExcecutorConfig.getExcecutorConfig().getFlinkxHome(), tmpFilePath,jobId);
			for (int j = 0; j < cmdarrayFinal.length; j++) {
				cmdstr += cmdarrayFinal[j] + " ";
			}
			ExecutorService executor = Executors.newFixedThreadPool(10);
			String finalCmdstr = cmdstr;
			String finalTmpFilePath = tmpFilePath;
			Future<Integer> result = executor.submit(new Callable<Integer>() {
				public Integer call() throws Exception {
					// 异步处理的代码
					logger.info("Process ExecutorService =========");
					Process process = Runtime.getRuntime().exec(finalCmdstr);
					String prcsId = ProcessUtil.getProcessId(process);
					JobLogger.log("Execute: " + finalCmdstr);
					JobLogger.log("process id: " + prcsId);
					if (FileUtil.exist(finalTmpFilePath)) {
						//				FileUtil.del(new File(tmpFilePath));
					}
					// 记录日志
					Calendar calendar = Calendar.getInstance();
					calendar.setTime(new Date());
					calendar.set(Calendar.MILLISECOND, 0);
					Date triggerTime = calendar.getTime();
					JobLog jobLog = new JobLog();
					jobLog.setJobGroup(jobInfo.getJobGroup());
					jobLog.setJobId(jobInfo.getId());
					jobLog.setTriggerTime(triggerTime);
					jobLog.setJobDesc(jobInfo.getJobDesc());
					jobLog.setHandleTime(triggerTime);
					jobLog.setTriggerCode(ReturnT.SUCCESS_CODE);
					jobLog.setHandleCode(0);
					jobLog.setProcessId(prcsId);
					// 设置job的执行路径
					//jobLog.setExecutorAddress(cmdarrayFinal[3]);
					JobAdminConfig.getAdminConfig().getJobLogMapper().save(jobLog);
					return 1;
				}
			});

			// 在主线程中处理异步方法的返回值
			int value = result.get();

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

**Comment by alldatadc** [comment]
LGTD,我们会跟进解决这个issue,感谢您,respect!!

**Comment by alldatadc** [comment]
#598 fixed
