### ISSUE TITLE
[Bug][元数据管理]数据授权支持修改角色组

### ISSUE THREAD

**Issue by wushen123456** [alldatacenter/alldata#586]

**Comment by alldatadc** [comment]
LGTD,我们后续发版修复这个issue,感谢您

**Comment by alldatafounder** [comment]
新版本全新支持，原有流程的bug已经一一解决，开源项目会在下一个商业版稳定发布之后，对外开放内部开会讨论之后的功能bug。更稳定的版本应该在2024年6月，8月会发布
