### ISSUE TITLE
咨询下关于社区版，本地启动无法登录的问题

### ISSUE THREAD

**Issue by yichu2006** [alldatacenter/alldata#591]
1、后端必须启动的服务，已经启动了
![b199c5508117f5a49b8e20e852aa8a0](https://github.com/alldatacenter/alldata/assets/31680599/64ec4c11-6d64-4670-b0a5-ea9f3d745392)
2、通过 eureka 注册中心，已经有  config、gateway、service-system 服务
![063247b955d4f118472950d6726935f](https://github.com/alldatacenter/alldata/assets/31680599/363c8ca5-00ac-4950-861f-8ff59d28b2e4)
3、前端启动访问，依然报错。找不到 auth
![5a92aeb8e6150182be3512b52403243](https://github.com/alldatacenter/alldata/assets/31680599/9ac51f87-5f33-43bc-bc6c-1fd6c889a604)

**Comment by yichu2006** [comment]
4、网关报错如下：
![58a0b82a889144f8393022cae7a40c8](https://github.com/alldatacenter/alldata/assets/31680599/4c47e1f5-d193-4a93-b0ac-2391365e0d5c)

**Comment by caicaineverbug** [comment]
你再重启 system 服务应该就好了    不行就连gateway  也重启下  应该就好了

**Comment by alldatadc** [comment]
> 你再重启 system 服务应该就好了 不行就连gateway 也重启下 应该就好了

是的，感谢您！！依次重启system-service,gateway服务，检查日志排查应该可以解决

**Comment by alldatadc** [comment]
> 4、网关报错如下： ![58a0b82a889144f8393022cae7a40c8](https://user-images.githubusercontent.com/31680599/246707618-4c47e1f5-d193-4a93-b0ac-2391365e0d5c.png)

您好，可以尝试重启解决
依次重启system-service,gateway服务，检查日志排查应该可以解决
