### ISSUE TITLE
系统工具-储存管理  上传报错

### ISSUE THREAD

**Issue by caicaineverbug** [alldatacenter/alldata#593]
![1687250056786](https://github.com/alldatacenter/alldata/assets/51841300/c75c46dd-794a-495d-b999-a30618b8bb53)

FileUtil.getSize(multipartFile.getSize())  中  multipartFile文件  在方法 file.transferTo(dest);  时  tmp下文件已经被删除 导致报错
改为  FileUtil.getSize(file.length()) 恢复正常

![1687250166236](https://github.com/alldatacenter/alldata/assets/51841300/7a3c1c7e-2435-4caa-b644-5d17c54cb8cc)

**Comment by alldatadc** [comment]
#598 fixed
