### ISSUE TITLE
部署完数据质量模块缺少规则引擎、日志监控和质量统计

### ISSUE THREAD

**Issue by wubolive** [alldatacenter/alldata#603]
<img width="441" alt="image" src="https://github.com/alldatacenter/alldata/assets/31678260/60de5476-7e8d-4cf5-9a4f-cfe581f6d002">

如题，请问这是商业版功能吗？还有如何进群呢？

**Comment by alldatadc** [comment]
您的问题可以通过配置菜单解决，如果您部署了一套，需要给自己的角色配置菜单就可以
目前开源的功能有文档描述，或者查看最新的ReleaseV0.4.2 
这是文档入口：https://docs.qq.com/doc/DVHlkSEtvVXVCdEFo
