### ISSUE TITLE
[Bug][数据资产]提交数据模型的时候提示没有业务流程对象

### ISSUE THREAD

**Issue by 24926691** [alldatacenter/alldata#604]
![微信图片_20230713093806](https://github.com/alldatacenter/alldata/assets/77082646/b88a484a-5558-4128-9842-aa10501848f9)
![微信图片_20230713093759](https://github.com/alldatacenter/alldata/assets/77082646/42b16c33-8a14-46c9-9977-2e392e546a88)

**Comment by huizhoujava** [comment]
+1

**Comment by alldatafounder** [comment]
旧版本遗留问题已经在新版本得到解决，新版本1.2.0全新会员商业版发布之后，开源社区版有进行迭代更新。
