### ISSUE TITLE
打包生产部署，走nginx转发,IP访问不到。

### ISSUE THREAD

**Issue by sunquans** [alldatacenter/alldata#605]
问题背景：安装alldata到 生产环境启动前端ui项目, 需要[配置nginx] 然后IP访问不到正确端口
![image](https://github.com/alldatacenter/alldata/assets/112848207/6b88023e-46c3-4fe6-9101-0d596693cc7a)
![image](https://github.com/alldatacenter/alldata/assets/112848207/c5d70202-5941-4ca2-b5b7-89fd74bc2b5e)
![image](https://github.com/alldatacenter/alldata/assets/112848207/3539d0e1-5ec4-4334-bbd0-18d22a95ec87)

安装模式：3节点
集群环境：
[root@master nginx]# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

 nginx配置：
![image](https://github.com/alldatacenter/alldata/assets/112848207/3305c29a-9a75-482c-9c5b-6feb618d95a6)

**Comment by sunquans** [comment]
现在用ip不用端口可以访问到了，但是报错 接口请求失败
![image](https://github.com/alldatacenter/alldata/assets/112848207/84e5d073-646b-46fa-a89b-004b83c36592)

**Comment by HZNU-Qiu** [comment]
您好，我也遇到了和您类似的问题，说是“Access-Control-Allow-Origin只允许有一个值，而响应头里有多个Origin；”也是首页验证码加载不出来，但是能请求的到。nginx我尝试删除跨域请求的配置，但是还是不行。请问您遇到的是这个问题吗，如果是的请问您是如何解决的呀？

**Comment by saltsodawater** [comment]
我遇到了同样的问题，请问解决了嘛，是如何解决的呀
