### ISSUE TITLE
元数据管理-数据源  同步状态怎么操作数据同步

### ISSUE THREAD

**Issue by sunquans** [alldatacenter/alldata#606]
![image](https://github.com/alldatacenter/alldata/assets/112848207/315e6179-7886-48f0-a458-c22a1d390edc)

**Comment by sunquans** [comment]
![image](https://github.com/alldatacenter/alldata/assets/112848207/74fae9cb-98ab-4330-84af-7af28778b246)
数据同步失败的log日志在哪看

**Comment by sunquans** [comment]
![3b8c8dc2a8bc00a11e8458c40636a16](https://github.com/alldatacenter/alldata/assets/112848207/925c2f84-a98e-4b82-ba1d-86cfe2ea6821)
元数据管理中的SQL控制台 输入错误语法之后 看不到报错信息，去后台应该怎么看日志。

**Comment by alldatadc** [comment]
这个是metadata-console的后端日志，可以查看metadata-sql-console.log，具体可以查看alldata/studio/install你的安装路径去查看对应的日志，先找到metadata-sql-console.sh里面有描述日志路径
