### ISSUE TITLE
数据模型刷新报错

### ISSUE THREAD

**Issue by koihuang** [alldatacenter/alldata#607]
分支：master分支
时间：2023.07.17
本地部署成功，试用过程中发现页面刷新会有问题，比如数据模型，如果从页面导航点到数据模型显示正常，如果从这个地址：http://localhost:8013/masterdata/datamodel 直接进入或者浏览器刷新该页面地址就会报错。
![image](https://github.com/alldatacenter/alldata/assets/38130681/d6587c79-cb60-4535-b255-6630cd3a0094)
![image](https://github.com/alldatacenter/alldata/assets/38130681/77bf1719-becf-4a97-9bd1-fedbe6f70020)

我看大部分菜单的地址都会有这个问题，是不是项目本身不支持浏览器本身自带的刷新后退等操作？

**Comment by Kingsuperyzy** [comment]
将前端代码 ui/src/router/routers.js 里的第94行 mode: 'history', 注释掉就好了

**Comment by alldatadc** [comment]
> 将前端代码 ui/src/router/routers.js 里的第94行 mode: 'history', 注释掉就好了

您好，可以给我们提交一个PR,感谢您，也欢迎您成为我们AllData社区的contributors
