### ISSUE TITLE
添加mongo数据源时，连通性检测没有提示，数据同步时显示失败

### ISSUE THREAD

**Issue by suptem** [alldatacenter/alldata#609]
![image](https://github.com/alldatacenter/alldata/assets/19321953/06978349-8c1f-4471-9e5a-78f4a3bb9c4d)
![image](https://github.com/alldatacenter/alldata/assets/19321953/8cb27567-b9fe-499e-b560-761988c81077)
还有就是添加数据库连接的时候用户名必填，那我加入redis数据源时就无法加入了，请问这个怎么处理
![image](https://github.com/alldatacenter/alldata/assets/19321953/03b057fc-00e6-453a-b958-99f6b8de2f94)

**Comment by ProductManage-Leo** [comment]
mongo,redis似乎还没有支持，具体我们内部开会讨论下
