### ISSUE TITLE
头像问题--前端到gateway 转发问题

### ISSUE THREAD

**Issue by Hezheng2023** [alldatacenter/alldata#622]
头像存储地址是106 取图片地址却是108

推测应该应该是前端到gateway转发的问题   .env.development文件中的地址是108网关地址

**Comment by Hezheng2023** [comment]
![image](https://github.com/alldatacenter/alldata/assets/128333131/9c081bf0-88b4-41ac-9e1c-efcf473427aa)
![efd9dce9e2d19b5818618357638f92e](https://github.com/alldatacenter/alldata/assets/128333131/7f272c4e-d869-49e1-a401-b70e8fdbb0e5)

**Comment by alldatadc** [comment]
修改两处获取头像的uri前缀可以解决这个issue
原来的：baseApi + '/avatar/ 
修改后：baseApi + '/system/avatar/
第1处：alldata/studio/ui/src/layout/components/Navbar.vue 
第2处：alldata/studio/ui/src/views/system/user/center.vue

修改后效果：
<img width="1135" alt="image" src="https://github.com/alldatacenter/alldata/assets/20246692/f16ca1a7-f996-4f12-b9f7-636047bce59d">

**Comment by alldatadc** [comment]
后续发版会发布，可以提前改下
