### ISSUE TITLE
[Bug] 元数据管理-数据源页面状态文字无法显示

### ISSUE THREAD

**Issue by beautydoudou** [alldatacenter/alldata#626]
![image](https://github.com/alldatacenter/alldata/assets/81671856/66c0eb3c-1f42-4ab0-961e-a870d507937a)

该问题也会导致启用禁用 单选框不能单选,下拉选不能正常使用
![image](https://github.com/alldatacenter/alldata/assets/81671856/eee3fd89-75e4-44c7-bf5b-c340ba2720a0)

![image](https://github.com/alldatacenter/alldata/assets/81671856/ebfc0d5b-0cf2-464e-ab88-5cf143a39860)
![image](https://github.com/alldatacenter/alldata/assets/81671856/8a4c74a6-c9d8-49af-a14b-14b2dd35a9c0)

**Comment by alldatafounder** [comment]
we had fixed this issue. 新版会发布解决这个问题

1、元数据管理-数据源状态已经正常展示。创建数据源k可以正常选择禁用/启用数据源
<img width="1977" alt="image" src="https://github.com/alldatacenter/alldata/assets/20246692/571d329a-484b-44ce-833a-32131555bb79">

2、数据市场-数据服务，服务类型问题已修复
<img width="710" alt="image" src="https://github.com/alldatacenter/alldata/assets/20246692/a59979ab-7950-4394-9631-39c6008e278b">
