### ISSUE TITLE
[Bug][元数据管理]数据源选择任意类型的数据库显示为mysql数据库

### ISSUE THREAD

**Issue by beautydoudou** [alldatacenter/alldata#627]
![image](https://github.com/alldatacenter/alldata/assets/81671856/259152c2-cfed-4510-812d-f84e781174e8)
该问题可能导致测试数据源连通时 报错 提示为无效数据库类型
![image](https://github.com/alldatacenter/alldata/assets/81671856/290eb016-a9bc-45fc-b846-69cf4088eda3)

**Comment by alldatafounder** [comment]
新版本没有这个问题，如果选择了oracle本地实例数据库，连接不上会报错
<img width="1245" alt="image" src="https://github.com/alldatacenter/alldata/assets/20246692/8d0647d9-d341-400b-9356-f1128df9f22c">
