### ISSUE TITLE
前端登录报错，缺少loadMenus函数，代码里也没找到这个函数，项目版本Release0.4.2

### ISSUE THREAD

**Issue by wangpan3** [alldatacenter/alldata#630]
前端登录报错，缺少loadMenus函数，代码里也没找到这个函数，版本Release0.4.2

**Comment by wangpan3** [comment]
![image](https://github.com/alldatacenter/alldata/assets/16097912/916c849f-604b-4bb0-bd6e-61d21fecfca7)

**Comment by wangpan3** [comment]
![ed2fb743a1869e7d995fffbfabff76c](https://github.com/alldatacenter/alldata/assets/16097912/0d502180-271d-4129-99de-739a838a3c75)

**Comment by alldatadc** [comment]
问题复现已确认是issue，我安排社区伙伴周末解决，并在社区群里回复

**Comment by alldatadc** [comment]
fixed 
https://github.com/alldatacenter/alldata/commit/e123744dc500f6cc6211ea1cfdd81f82292eb9ca
