### ISSUE TITLE
 前端通过Nodejs v10.15.3 可成功编译项目，但是项目运行出错

### ISSUE THREAD

**Issue by snowfield516** [alldatacenter/alldata#631]
运行npm run dev后出现错误
![image](https://github.com/alldatacenter/alldata/assets/4134369/2aa44434-eec8-4727-b2b9-236237da18b5)

**Comment by alldatadc** [comment]
经判断此问题未复现。
运行命令如下：nvm use v10.15.3,
1、进行npm install，成功
<img width="506" alt="image" src="https://github.com/alldatacenter/alldata/assets/20246692/7736cf43-61a2-4ef2-93ab-9c9826ca8781">
2、npm run build:prod, 成功打包
<img width="641" alt="image" src="https://github.com/alldatacenter/alldata/assets/20246692/54e8590f-e223-4457-be3c-7d7e3a565199">
3、npm run dev, 成功本地运行
<img width="486" alt="image" src="https://github.com/alldatacenter/alldata/assets/20246692/a17c7c49-4314-49f5-80e7-4986b170b541">
