### ISSUE TITLE
data-compare-service在eureka注册中心的问题

### ISSUE THREAD

**Issue by WuQingShan1** [alldatacenter/alldata#634]
github上面data-compare-service的bootstrap.yml ,euraka这里的ip-address是localhost, 服务器部署测试时改成了16gmaster,但是在eureka注册中心点击服务跳转的连接还是http://localhost:8096/actuator/info。

**Comment by AllDataDC** [comment]
已确认是问题，后续发版会修改为16gmaster，localhost不再保留
localhost只适合本地调试启动
