### ISSUE TITLE
任务执行无效，直接手动cmd直接生成json成功。

### ISSUE THREAD

**Issue by jeff06143132** [alldatacenter/alldata#647]
创建单任务，并在 数据集成 - 任务详情 菜单中，操作 “执行一次” ， 实际任务并未执行，也无执行日志结果。
![741b99fc82fc3ea3483cba62c80161f](https://github.com/alldatacenter/alldata/assets/22599109/cf70d2ec-8d17-4851-ad5d-9560bf8db592)
![a8c94423495f1ce2b73c648806969bf](https://github.com/alldatacenter/alldata/assets/22599109/758b3594-bb7d-46b6-bdf1-db4f649e1fa1)
![85b432539be04427aacafa337b3eca5](https://github.com/alldatacenter/alldata/assets/22599109/13d065d1-695a-46df-8dce-69379b12e5cf)

**Comment by jeff06143132** [comment]
`com.platform.admin.core.thread.JobTriggerPoolHelper#runJob`

**Comment by jeff06143132** [comment]
process.waitFor();

**Comment by jeff06143132** [comment]
`public static void runJob(int jobId) {
		InputStreamReader isReader = null;
		BufferedReader bfReader = null;
    	try {
			JobInfo jobInfo = JobAdminConfig.getAdminConfig().getJobInfoMapper().loadById(jobId);
			String cmdstr = "";
			String tmpFilePath ="";
			String[] cmdarrayFinal = null;
			tmpFilePath = generateTemJsonFile(jobInfo.getJobJson());
			cmdarrayFinal = buildFlinkXExecutorCmd(ExcecutorConfig.getExcecutorConfig().getFlinkxHome(), tmpFilePath,jobId);
			for (int j = 0; j < cmdarrayFinal.length; j++) {
				if (cmdarrayFinal[j].contains(".out")) {
					cmdstr += " > " + cmdarrayFinal[j] ;
				}else {
					cmdstr += cmdarrayFinal[j] + " ";
				}
			}
			if(cmdstr.indexOf("python")>0){
				cmdstr = cmdstr.substring(cmdstr.indexOf("python"), cmdstr.length());
			}
			final Process process = Runtime.getRuntime().exec(cmdstr);
			String prcsId = ProcessUtil.getProcessId(process);
			JobLogger.log("Execute7: " + cmdstr);
			JobLogger.log("process id: " + prcsId);
			//jeff优化直接执行不生效问题
			isReader = new InputStreamReader(process.getInputStream(), "UTF-8");
			bfReader = new BufferedReader(isReader);
			String line = null;
			while ((line = bfReader.readLine()) != null){
				logger.info(line);
			}
			process.waitFor();
			JobLogger.log("Execute8: " + cmdstr);
			if (FileUtil.exist(tmpFilePath)) {
				//				FileUtil.del(new File(tmpFilePath));
			}
			// 记录日志
			Calendar calendar = Calendar.getInstance();
			calendar.setTime(new Date());
			calendar.set(Calendar.MILLISECOND, 0);
			Date triggerTime = calendar.getTime();
			JobLog jobLog = new JobLog();
			jobLog.setJobGroup(jobInfo.getJobGroup());
			jobLog.setJobId(jobInfo.getId());
			jobLog.setTriggerTime(triggerTime);
			jobLog.setJobDesc(jobInfo.getJobDesc());
			jobLog.setHandleTime(triggerTime);
			jobLog.setTriggerCode(ReturnT.SUCCESS_CODE);
			jobLog.setHandleCode(0);
			jobLog.setProcessId(prcsId);
			// 设置job的执行路径
			//jobLog.setExecutorAddress(cmdarrayFinal[3]);
			JobAdminConfig.getAdminConfig().getJobLogMapper().save(jobLog);
			JobLogger.log("jobLogV: " + jobLog);
		} catch (Exception e) {
			e.printStackTrace();
		}finally {
    		if(bfReader != null){
				try {
					bfReader.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
    		if(isReader != null){
				try {
					isReader.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
	}`

**Comment by jeff06143132** [comment]
public static void runJob(int jobId) {
		InputStreamReader isReader = null;
		BufferedReader bfReader = null;
    	try {
			JobInfo jobInfo = JobAdminConfig.getAdminConfig().getJobInfoMapper().loadById(jobId);
			String cmdstr = "";
			String tmpFilePath ="";
			String[] cmdarrayFinal = null;
			tmpFilePath = generateTemJsonFile(jobInfo.getJobJson());
			cmdarrayFinal = buildFlinkXExecutorCmd(ExcecutorConfig.getExcecutorConfig().getFlinkxHome(), tmpFilePath,jobId);
			for (int j = 0; j < cmdarrayFinal.length; j++) {
				if (cmdarrayFinal[j].contains(".out")) {
					cmdstr += " > " + cmdarrayFinal[j] ;
				}else {
					cmdstr += cmdarrayFinal[j] + " ";
				}
			}
			if(cmdstr.indexOf("python")>0){
				cmdstr = cmdstr.substring(cmdstr.indexOf("python"), cmdstr.length());
			}
			final Process process = Runtime.getRuntime().exec(cmdstr);
			String prcsId = ProcessUtil.getProcessId(process);
			JobLogger.log("Execute7: " + cmdstr);
			JobLogger.log("process id: " + prcsId);
			//jeff优化直接执行不生效问题
			isReader = new InputStreamReader(process.getInputStream(), "UTF-8");
			bfReader = new BufferedReader(isReader);
			String line = null;
			while ((line = bfReader.readLine()) != null){
				logger.info(line);
			}
			process.waitFor();
			JobLogger.log("Execute8: " + cmdstr);
			if (FileUtil.exist(tmpFilePath)) {
				//				FileUtil.del(new File(tmpFilePath));
			}
			// 记录日志
			Calendar calendar = Calendar.getInstance();
			calendar.setTime(new Date());
			calendar.set(Calendar.MILLISECOND, 0);
			Date triggerTime = calendar.getTime();
			JobLog jobLog = new JobLog();
			jobLog.setJobGroup(jobInfo.getJobGroup());
			jobLog.setJobId(jobInfo.getId());
			jobLog.setTriggerTime(triggerTime);
			jobLog.setJobDesc(jobInfo.getJobDesc());
			jobLog.setHandleTime(triggerTime);
			jobLog.setTriggerCode(ReturnT.SUCCESS_CODE);
			jobLog.setHandleCode(0);
			jobLog.setProcessId(prcsId);
			// 设置job的执行路径
			//jobLog.setExecutorAddress(cmdarrayFinal[3]);
			JobAdminConfig.getAdminConfig().getJobLogMapper().save(jobLog);
			JobLogger.log("jobLogV: " + jobLog);
		} catch (Exception e) {
			e.printStackTrace();
		}finally {
    		if(bfReader != null){
				try {
					bfReader.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
    		if(isReader != null){
				try {
					isReader.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
	}

**Comment by alldatafounder** [comment]
感谢您，可以提交PR

**Comment by xjdAlan** [comment]
使用process.waitFor();还是不行。
看该函数是等待process进程执行结束，但是process进程一直不结束，导致程序一直阻塞在这里了。

**Comment by xjdAlan** [comment]
https://blog.csdn.net/weixin_42267411/article/details/128552056

**Comment by alldatafounder** [comment]
[Feature][studio]thanks @jeff06143132,解决数据集成直接执行任务失败的问题,日志问题#647
修改详情：
https://github.com/alldatacenter/alldata/commit/2dc05ef6adbbae83283e06c96ec0e920ec7af9f0
