### ISSUE TITLE
下载最新分支的代码啊，初始化数据库mysql5.7和8导入sql脚本都会报错

### ISSUE THREAD

**Issue by cfs1999** [alldatacenter/alldata#648]
下载最新分支的代码啊，初始化数据库mysql5.7和8导入sql脚本都会报错
![0d5183d45da9d8a5b09dcdaa3c3a674](https://github.com/alldatacenter/alldata/assets/138541949/b66fff63-1b46-414a-8111-4aa723191086)

**Comment by AllDataDC** [comment]
安装教程是alldata/install.md, 清空原来的数据库, 重新按顺序执行sql脚本
1、studio数据库初始化
1.1 source install/sql/studio.sql 
1.2 source install/sql/studio-v0.x.x.sql
