### ISSUE TITLE
system和config处的配置有误,本地部署.

### ISSUE THREAD

**Issue by papa465** [alldatacenter/alldata#660]
![4da36802c16e0d4a357a28b38396065](https://github.com/alldatacenter/alldata/assets/79949174/ed35dcc7-6868-489e-89f8-82e07d581518)
![fc2af560f88382b06db9bd816c58cfa](https://github.com/alldatacenter/alldata/assets/79949174/41cc5f7b-59d6-4041-84fe-493f85e5d801)

这是我的system和config处的配置,本地部署.
更改处是这样的,我应该怎么修改.
![image](https://github.com/alldatacenter/alldata/assets/79949174/b2de25d1-9a42-4966-9173-92d18a94f17e)
![image](https://github.com/alldatacenter/alldata/assets/79949174/3aaa22a5-3057-46f5-aa0f-dddf52c0be21)

**Comment by alldatafounder** [comment]
system-service配置localhost正确，尝试重启config,gateway,eureka,system-service
