### ISSUE TITLE
数据集成 模块启动——java.io.IOException: Could not locate executable null\bin\winutils.exe

### ISSUE THREAD

**Issue by QiuZiXian** [alldatacenter/alldata#672]
17:48:09.668 admin [main] ERROR o.a.h.u.Shell - Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
service-data-dts-parent ~ service-data-dts ~ DataDtsServiceApplication模块启动error：
![image](https://github.com/alldatacenter/alldata/assets/28780269/1560924c-1d7e-467e-88cd-6aa22120b8ac)

**Comment by alldatafounder** [comment]
windows和hadoop这个集成问题不影响，可以服务器部署使用。
