### ISSUE TITLE
[Bug][数据资产]数据管理数据权限问题

### ISSUE THREAD

**Issue by QiuZiXian** [alldatacenter/alldata#673]
你好，请问一下数据权限问题，是否支持，比如a、b用户只能看到自己的数据模型。
![5a0640b772775c10f0b4b4c8cc3e66f](https://github.com/alldatacenter/alldata/assets/28780269/7213a408-ff75-46ea-acb7-5516895b1128)
![0e2f0f07509ae80380d412c2b362ed9](https://github.com/alldatacenter/alldata/assets/28780269/8f003991-2a66-4833-ab7c-6081c2ac6623)

**Comment by alldatafounder** [comment]
新版本已经支持用户查看自身创建的模型，待下一个版本发布到正式环境后解决此问题
新版本正式环境地址：http://122.51.43.143:5173/ui_moat/ 账号密码： test/123456
