### ISSUE TITLE
maven依赖下载问题

### ISSUE THREAD

**Issue by LMR-up** [alldatacenter/alldata#675]
在根目录下，执行mvn install报错，是网络问题，还是？？
Failed to execute goal on project common-office: Could not resolve dependencies for project com.platform:common-office:jar:0.4.x: com.aspose:asp
ose-words:jar:20.3 was not found in http://maven.aliyun.com/nexus/content/repositories/central/ during a previous attempt. This failure was cached in th
e local repository and resolution is not reattempted until the update interval of alimaven has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by LMR-up** [comment]
根据文档在根目录，执行install..然后显示aspose-words:jar:20.3下载不下来，但是本地是有下载好的jar文件在common项目下面
![image](https://github.com/alldatacenter/alldata/assets/80820139/c56c7c8f-8cec-419a-bf94-d5bd2847dc41)

**Comment by LMR-up** [comment]
以解决

**Comment by LMR-up** [comment]
新问题，新问题，大佬快帮我看看 登录的时候数据库连接池连接错误，卡顿在登录界面
![image](https://github.com/alldatacenter/alldata/assets/80820139/34f41993-8ebd-42d7-98d2-14d747fec1f6)

**Comment by alldatafounder** [comment]
调大mysql connection.

**Comment by LMR-up** [comment]
rabbitmq单机可以吗，不需要集群吧
