### ISSUE TITLE
AllData Release v0.4.3 中studio-v0.3.8.sql文件运行失败

### ISSUE THREAD

**Issue by FIRSTBIGMAOMAO** [alldatacenter/alldata#676]
在运行AllData Release v0.4.3版中的studio.sql、studio-v0.3.7.sql、studio-v0.3.8.sql、studio-v0.3.9.sql四个文件中studio.sql和studio-v0.3.8.sql存在外键问题。
下图为studio.sql文件中一部分：

![WechatIMG19](https://github.com/alldatacenter/alldata/assets/58461591/409c3322-7f8b-4105-b48e-e312ca6e0680)

下图为studio-v0.3.8.sql文件中的一部分：

![WechatIMG21](https://github.com/alldatacenter/alldata/assets/58461591/64210c3f-df9e-4cd3-b96e-e7b2cca113f0)

数据库已经设置大小写敏感，但是在创建时还是提示外键问题，情况如下：

![WechatIMG23](https://github.com/alldatacenter/alldata/assets/58461591/ae9d4e2e-169f-4429-94ad-8b203197576d)

**Comment by alldatafounder** [comment]
可以重新导入database, 删除后重新创建数据库studio,我近期服务器部署没有这个问题

**Comment by FIRSTBIGMAOMAO** [comment]
能详细说一下数据库的版本和相关配置吗，我今天重新部署了，还存在问题，我怀疑是数据库这一块出了问题。多谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月2日(星期四) 下午5:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alldatacenter/alldata] AllData Release v0.4.3 中studio-v0.3.8.sql文件运行失败 (Issue #676)





 
可以重新导入database, 删除后重新创建数据库studio,我近期服务器部署没有这个问题
