### ISSUE TITLE
前端项目请求转发问题

### ISSUE THREAD

**Issue by LMR-up** [alldatacenter/alldata#677]
![image](https://github.com/alldatacenter/alldata/assets/80820139/13a593c3-56b2-4961-a597-7f17120c7923)
![image](https://github.com/alldatacenter/alldata/assets/80820139/be5d9110-bcc8-4d5a-9f6e-4f35c22f0f1b)
请问这是没发起请求还是转发失败，但是直接访问这个url却可以返回code
![image](https://github.com/alldatacenter/alldata/assets/80820139/74f7609d-bb06-46d8-ac0e-23bc9f83b466)
以下是我的前端设置
![image](https://github.com/alldatacenter/alldata/assets/80820139/88018483-eb94-4219-b046-a7ac6e20f4c2)
yi以下是我的nginx设置
![image](https://github.com/alldatacenter/alldata/assets/80820139/1bd7108f-95dc-487e-b666-639661632634)
请您帮忙看下

**Comment by LMR-up** [comment]
已解决，后端设置了https，但是前端的
![image](https://github.com/alldatacenter/alldata/assets/80820139/2761e0ef-3ba0-4fc6-b62e-9b279fcd9b50)

**Comment by alldatafounder** [comment]
恭喜您成功体验AllData!!
