### ISSUE TITLE
rabbitmq链接不上

### ISSUE THREAD

**Issue by LMR-up** [alldatacenter/alldata#678]
rabbitmq链接不上
![image](https://github.com/alldatacenter/alldata/assets/80820139/d534e010-aba7-4a14-96b7-b0e0991afce9)
![image](https://github.com/alldatacenter/alldata/assets/80820139/288f8f5a-944c-4be1-b0e0-bc66f0d4ce43)
![image](https://github.com/alldatacenter/alldata/assets/80820139/83f84ec8-7aa6-44b9-9f6f-4ee4b9437308)
![image](https://github.com/alldatacenter/alldata/assets/80820139/670e1534-87ce-4365-a0df-1600093d50b1)

**Comment by alldatafounder** [comment]
设置rabbitmq远程免密

**Comment by LMR-up** [comment]
这个咋设置阿，配置文件？，我只找到开放远程访问的做法

**Comment by LMR-up** [comment]
谢谢已解决
