### ISSUE TITLE
数据图表预览错误

### ISSUE THREAD

**Issue by LMR-up** [alldatacenter/alldata#682]
预览图表请求
![image](https://github.com/alldatacenter/alldata/assets/80820139/9a92d3cb-180d-4cd2-ba6e-e931dc7add4d)
![image](https://github.com/alldatacenter/alldata/assets/80820139/06bc5808-8832-4710-b40e-fe80bd38e0c4)

![image](https://github.com/alldatacenter/alldata/assets/80820139/c21328b8-d7e1-4954-81ce-56e4ced24bf1)
是因为相关服务没有启动吗

**Comment by LMR-up** [comment]
补充
![image](https://github.com/alldatacenter/alldata/assets/80820139/98389673-f01e-41b9-9af1-2f514f7481d7)

**Comment by alldatafounder** [comment]
fixed #694
thanks a lot!! respect!!
