### ISSUE TITLE
体验服数据图表预览失败

### ISSUE THREAD

**Issue by LMR-up** [alldatacenter/alldata#683]
![image](https://github.com/alldatacenter/alldata/assets/80820139/5d397e78-db14-4f18-893b-5bd08756bf5a)

**Comment by LMR-up** [comment]
数据看板也是预览失败
![image](https://github.com/alldatacenter/alldata/assets/80820139/44039cb5-3758-4d82-ad77-c156338de769)

**Comment by alldatafounder** [comment]
fixed #694, 后续会升级体验版BI, 感谢您！！
thanks a lot!! respect!!
