### ISSUE TITLE
[Bug][元数据管理]数据字段详情多次变更后，变更记录无变更信息

### ISSUE THREAD

**Issue by jeff06143132** [alldatacenter/alldata#692]
![1111](https://github.com/alldatacenter/alldata/assets/22599109/63ce6739-c8ed-44f4-a4d5-88e7a1039c92)

**Comment by alldatafounder** [comment]
<img width="2196" alt="image" src="https://github.com/alldatacenter/alldata/assets/20246692/091992b7-2152-4322-af50-82b79ea30964">
we had fixed this issue， 新版本没有这个问题
