### ISSUE TITLE
[Bug][数据集成] mongo作为目标源无法配置任务

### ISSUE THREAD

**Issue by alldatafounder** [alldatacenter/alldata#698]

**Comment by DirkJia** [comment]
@i will try solve it@

**Comment by alldatafounder** [comment]
Thanks a lot, Respect!!

**Comment by alldatafounder** [comment]
Not Planned.

AllData数据集成功能用datax,flinkx，新版本支持了flinkcdc。
后续会在页面上支持以上3个不同类型的同步插件进行数据同步。
1、datax支持mongodb同步 https://blog.csdn.net/u010834071/article/details/114939483
2、flinkx可以查看https://dtstack.github.io/chunjun-web/docs/chunjunDocs/connectors/mongodb/mongodb-source
3、flinkcdc支持mongo进行cdc
