### ISSUE TITLE
首次本地运行已成功，过程遇到几个问题

### ISSUE THREAD

**Issue by songlai** [alldatacenter/alldata#701]
本地运行，所有 Erueka 相关都改成了localhost
1. 前端使用  10.15.3 在 npm install 时失败，使用 10.24.1 后成功。
2. 服务运行后验证码不能读取，接口获取错误。排查发现 gateway 的 config 服务地址是 localhost:8888，service-system的 config 是 localhost:8611。没找到怎么设置的，最后手动在gateway的bootstrap.yml中增加了spring.cloud.config.uri=http://localhost:8611重启后成功。
3. 如果想更改数据库名，在所有sql中查询use studio和create datebase studio 注释掉。

**Comment by alldatafounder** [comment]
npm用16.20.2就可以。
验证码问题检查gataway.log,config/gateway配置和system-service的bootstrap.yml配置，尝试重启gateway
