### ISSUE TITLE
[Bug] 数据集成单任务解析字段

### ISSUE THREAD

**Issue by hxh-plzshowme** [alldatacenter/alldata#705]
![image](https://github.com/alldatacenter/alldata/assets/52400580/db22d573-859b-4a58-a43c-8d5feb4098a6)
当我在sql中写了一个查询后，下方解析字段显示有误

**Comment by alldatafounder** [comment]
we had fixed this issue, 原因是状态码为0是接口code，不应该展示在前端
下一个版本解决
