### ISSUE TITLE
接口服务 - 接口文档报错

### ISSUE THREAD

**Issue by huhu-sky** [alldatacenter/alldata#713]
![image](https://github.com/alldatacenter/alldata/assets/12699301/aa99a4f8-b3a3-4119-8990-45b02f392386)
最后发现，应该是这个方法还没有实现：
![image](https://github.com/alldatacenter/alldata/assets/12699301/2307838e-d13b-4fc1-b9f6-12c1c8aed41e)

看是否有模板或者其它计划；

**Comment by huhu-sky** [comment]
发现在其配置文件下 templates 有 api_1.0.0.docx ; 有空我看给补一下；

**Comment by alldatafounder** [comment]
您好，感谢您，欢迎提交PR，respect!!

**Comment by alldatafounder** [comment]
this issue had fixed 下一个版本解决
