### ISSUE TITLE
BI大屏 - 数据图表 - 界面异常

### ISSUE THREAD

**Issue by huhu-sky** [alldatacenter/alldata#714]
![image](https://github.com/alldatacenter/alldata/assets/12699301/1390bf45-b6af-479c-9ae9-b3f028874eb6)
右下角无法展示， 图表预览也无法展示

**Comment by alldatafounder** [comment]
旧版本遗留问题已经在新版本得到解决，新版本1.2.0全新会员商业版发布之后，开源社区版有进行迭代更新。
