### ISSUE TITLE
上传头像一直提示失败

### ISSUE THREAD

**Issue by HelloJRay** [alldatacenter/alldata#728]
上传头像时一直提示失败，但是刷新页面后可以查看上传的新头像。
并且控制台提示错误： 
![image](https://github.com/alldatacenter/alldata/assets/20751416/43ba26b0-c333-46bd-af6e-0b8aeb3bb500)

**Comment by alldatafounder** [comment]
这是控制台多个跨域导致配置重复问题，您只需要保留gateway对跨域的统一配置(也就是config配置中心gateway-dev.yml里面的跨域配置），保证前端cros,后端crosFilter都注释掉。

**Comment by HelloJRay** [comment]
> 

好的，谢谢~~
使用网上的另一个方式也可以避免这个双重跨域问题，参考链接：[https://www.jianshu.com/p/bf997c524a58](url)
