### ISSUE TITLE
按照部署文档本地启动第四个服务SystemServiceApplication报错

### ISSUE THREAD

**Issue by liudanyang6** [alldatacenter/alldata#730]
本地运行的代码，eureka都改成了本地的localhost;数据库相关的IP，port,用户名，密码也已经修改；但是启动的时候还是有报错，请问是哪里的问题呢？
报错内容：Parameter 0 of constructor in com.platform.modules.mnt.service.impl.AppServiceImpl required a bean named 'entityManagerFactory' that could not be found.

Action:

Consider defining a bean named 'entityManagerFactory' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:65249', transport: 'socket'

Process finished with exit code 1
附件贴图：
![Uploading WX20240515-182320@2x.png…]()

**Comment by alldatafounder** [comment]
Not planned. 配置不对，issue图片并不可见，尝试mvn clean之后，删除本地maven依赖repository，然后重启启动。另外也可以通过启动服务来确保是不是只有当前system-service无法启动。很有可能是配置中心配置文件并不正确。
