### ISSUE TITLE
启动system-service ,无法启动 ，看报错好像是mapper没有正确注入

### ISSUE THREAD

**Issue by easonShan** [alldatacenter/alldata#749]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in com.platform.modules.mnt.service.impl.AppServiceImpl required a bean of type 'com.platform.modules.mnt.service.mapstruct.AppMapper' that could not be found.

Action:

Consider defining a bean of type 'com.platform.modules.mnt.service.mapstruct.AppMapper' in your configuration.

**Comment by alldatafounder** [comment]
Not planned. 商业版已修复相关问题
