### ISSUE TITLE
数据服务发布后，访问失败market-log

### ISSUE THREAD

**Issue by liweitmac** [alldatacenter/alldata#750]
创建成功并发布后的数据服务，在market-log中注册成功
<img width="1122" alt="image" src="https://github.com/alldatacenter/alldata/assets/12508435/7923ee86-f81f-47d7-9982-4a5a5f97a757">
但访问数据服务url的时候会报错
<img width="1124" alt="image" src="https://github.com/alldatacenter/alldata/assets/12508435/b331a936-9876-41e8-b24e-0843cd9e5bc4">

**Comment by alldatafounder** [comment]
Not planned. 商业版没有复现这个问题.
确保请求Header有api_key,api_secret.
