### ISSUE TITLE
数据集成-sqlserver连接报错

### ISSUE THREAD

**Issue by saltsodawater** [alldatacenter/alldata#758]
描述：添加sqlserver的数据源正常，但是执行任务时报错
报错信息：具体错误信息为：java.sql.SQLException: No suitable driver found for jdbc:jtds:sqlserver://localhost:1433/DatabaseName=web.
![image](https://github.com/user-attachments/assets/9ddff929-121a-42e6-b892-74295ca22dbe)

经检查账号、密码、数据库名称、IP、Port都没有问题，驱动也经过Maven配置了
![image](https://github.com/user-attachments/assets/b5aab699-8975-4194-ac95-ca570a821f66)

**Comment by alldatafounder** [comment]
数据集成功能，会联通Datax，确保datax.tar.gz安装之后，datax/plugins/reader/sqlserver-x.x.x/lib目录下有上传驱动类。详情查看数据集成教程。alldata/quickstart/quickstart_dts.md
