### ISSUE TITLE
启动提示跨域问题 说多了一层

### ISSUE THREAD

**Issue by suyongcheng123** [alldatacenter/alldata#760]
<img width="943" alt="微信图片_20240913110723" src="https://github.com/user-attachments/assets/0d70f5f6-eeae-4397-8dd3-6082ac77adb8">
<img width="627" alt="微信图片_20240913110735" src="https://github.com/user-attachments/assets/f0b0fdd5-02d2-4016-8520-68aa9cd13d30">
<img width="766" alt="微信图片_20240913110749" src="https://github.com/user-attachments/assets/9ceb9a4b-41e7-4c77-9902-68cc606cc2f0">
您好！部署服务器以后验证码出不来
![Uploading 微信图片_20240913110837.png…]()

页面直接访问这个code是好的

**Comment by suyongcheng123** [comment]
<img width="491" alt="微信图片_20240913111257" src="https://github.com/user-attachments/assets/09b32925-4d7f-4d50-a7b1-c5bef34cff31">
这是我的NG配置

**Comment by alldatafounder** [comment]
如果用了81端口，建议用默认的80.
用了81端口，排查.env.production中是http://10.1.200.5:81/api发起请求

**Comment by CoderKite** [comment]
哥，你这个问题解决了吗？
