### ISSUE TITLE
p6spy代理 启动data-masterdata-service.jar 报错

### ISSUE THREAD

**Issue by suyongcheng123** [alldatacenter/alldata#762]
<img width="801" alt="微信图片_20240913154906" src="https://github.com/user-attachments/assets/e4b43fee-1fe6-4d2f-af91-ee5a89ea93f0">
<img width="569" alt="微信图片_20240913154913" src="https://github.com/user-attachments/assets/11ee3181-5928-4073-bd0f-5b9eb0a36c9e">
启动data-masterdata-service.jar 报错  提示p6spy 问题 请问怎么解决

**Comment by alldatafounder** [comment]
1、这块配置没有问题。建议Debug本地调通所有代码，排查问题解决后，再部署。

2、可以查看别的微服务的jdbc datasource的配置，可以配置成druid连接配置到mysql。

3、不一定要使用p6spy，这块需要检查是否下载了p6spy驱动。

4、建议直接修改config/application-common.yml的驱动配置，jdbcUrl配置，以及修改代码对jdbcUrl等属性的读取。
