### ISSUE TITLE
提示  lb://service-data-system/roles/list]失败，hystrix服务降级处理

### ISSUE THREAD

**Issue by suyongcheng123** [alldatacenter/alldata#763]
我在访问元数据管理- 数据授权时和 数据资产-数据模型时 提示：
网关执行请求:[http://10.1.200.5:9538/data/system/dicts/code/sys_flow_status, lb://service-data-system/dicts/code/sys_flow_status]失败，hystrix服务降级处理
![Uploading 微信图片_20240914101115.png…]()

**Comment by suyongcheng123** [comment]
<img width="812" alt="微信图片_20240914101115" src="https://github.com/user-attachments/assets/d3d1bd81-92be-4ff8-a501-29bd55d7d5eb">
提示网关执行请求:[http://10.1.200.5:9538/data/system/dicts/code/sys_flow_status, lb://service-data-system/dicts/code/sys_flow_status]失败，hystrix服务降级处理

**Comment by suyongcheng123** [comment]
然后已经重启了gateway还是不行

**Comment by alldatafounder** [comment]
1、确认下service-data-system的日志是否报错，这块是提供sys_flow_status的接口。

2、hystrix服务降级处理这个报错，可以查看报错的代码，原理是gateway找不到这个service-data-system的服务。如果重启过service-data-system, 确实可以通过重启gateway解决。

3、最后检查下gateway配置是否正确，检查config配置中心中gateway-dev.yml是否配置正确。
