### ISSUE TITLE
使用MySQL8.0时，config配置项中的驱动写死，导致报错Driver com.p6spy.engine.spy.P6SpyDriver claims to not accept jdbcUrl

### ISSUE THREAD

**Issue by HEEKDragonOne** [alldatacenter/alldata#767]
datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: ${common.mysql.master.url}
          username: ${common.mysql.master.username}
          password: ${common.mysql.master.password}
          
修改：
driver-class-name: com.mysql.cj.jdbc.Driver

**Comment by alldatafounder** [comment]
#768 Fixed
